language: node_js
sudo: false
node_js:
- '8'
before_install:
- npm i -g eslint eslint-watch
install:
- yarn install
script:
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: hB5GDN3CLwXldupgIfmdMtPiS2vJ9tnVtcegVIon3iGPWH0aOGh3pwRO53gfAFsNYFtRbWlMuFJi1kMW8YAtzPbNR3YraF0CD76zkqNxvAnEQ27aXAMFkTa2kDSrCsPucVsIzzTyu4gjp8ber2NTulTGPrPpSJ2qtRwD4O3pyso0QTs/5IIgS/NDtaIhlXTscdB50i3z8qD2zWfGcOSidX7H7x1WzzNJB2GpC3oxbAWQ4EBIrtwhPRgYerPvn077OmcYI5wLfvYWT2rwwry3wgpLT2cRuJ0yvP+KR0P3Xo+nJPMAlQNobX8LRlbdM2pEr/SYTuFhvP2totPRVi3BD3fnFjJZgB6CHgloe6RKuC3q/NsrUHt11rtOFuzozAWFBa0mP0z/QD7WxHgrUdF+vYSewVejBpf4+0UQOLKxhBOVrb4d4JKnLH/po1cG9Hh+KYn7hLmWneqT5C58H5m0UM3wQSIoz03RozwXTUzNsp05OKrinJe8hY9Am9hLAlsCLilsHfiApj0DhDL25AVKhhGDQ5bpRNEAXkxl7BcMODgrzETlFdbc6vY2IDxDFDVM5Kteyg2Xu321nq969u5c+kOp73IUAhe2REFXtmtDlRghEtmWR5v9TP6Et3KHoeSwA7bcY4K0DImkPuc3x5t9ejcg69EAl4NZzKlRLzjr00A=
